/// Dimensión de ambiente/track del pipeline: Producción (resultados/) vs Calidad (resultados_calidad/, con bandas LOYO P25-P75). Slicer de selección única sincronizado en las páginas de datos.
table Ambiente
	lineageTag: 0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c01

	column Ambiente
		dataType: string
		isKey
		lineageTag: 0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c02
		summarizeBy: none
		sourceColumn: AMBIENTE
		sortByColumn: Orden

	column Descripción
		dataType: string
		lineageTag: 0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c03
		summarizeBy: none
		sourceColumn: DESCRIPCION

	column Orden
		dataType: int64
		isHidden
		lineageTag: 0a1b2c3d-4e5f-4a6b-8c7d-9e0f1a2b3c04
		summarizeBy: none
		sourceColumn: ORDEN

	partition Partition = m
		mode: import
		source =
				let
				    Fuente = Table.FromRecords({[AMBIENTE="Producción", DESCRIPCION="Corrida oficial (resultados/)", ORDEN=1], [AMBIENTE="Calidad", DESCRIPCION="Track de calidad con bandas LOYO P25-P75 (resultados_calidad/)", ORDEN=2]}),
				    Tipos = Table.TransformColumnTypes(Fuente, {{"AMBIENTE", type text}, {"DESCRIPCION", type text}, {"ORDEN", Int64.Type}})
				in
				    Tipos

