/// FACT de curva M1: grilla densa Volumen/Delta vs Precio Aceite por Campo × Motor × Ambiente.
/// Alimenta las curvas continuas y bandas del Explorador; sin relación a Precio Brent (eje = precio aceite).
/// Los atributos del modelo (métodos, breakevens, baseline) viven en la DIM 'Modelo Campo'.
table 'Diagnóstico M1'
	lineageTag: 0c33e82c-94b8-446b-a38f-1e376aa50b3d

	column 'Campo Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: d3e362fa-6537-400a-8f19-452c09a3e80c
		summarizeBy: none
		sourceColumn: CAMPO

	column 'Motor Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: a0feef47-0487-481d-8e70-ca220085613d
		summarizeBy: none
		sourceColumn: MOTOR

	column 'Precio Aceite (USD/bbl)'
		dataType: double
		formatString: $#,##0.00
		lineageTag: 452914e5-a318-41a0-836f-7b2b801faa2d
		summarizeBy: sum
		sourceColumn: PRECIO_ACEITE_USD_BBL

		annotation SummarizationSetBy = Automatic

	column 'Delta Anclado (MBPE)'
		dataType: double
		formatString: #,##0.0
		lineageTag: cc121df9-7c23-43ae-b23a-5ea8955caae9
		summarizeBy: sum
		sourceColumn: DELTA_ANCLADO_MBPE

		annotation SummarizationSetBy = Automatic

	column 'Volumen 1P Predicho (MBPE)'
		dataType: double
		formatString: #,##0.0
		lineageTag: e0f62af2-792e-44e9-a0c7-05da32f53e47
		summarizeBy: sum
		sourceColumn: VOLUMEN_1P_PREDICHO_MBPE

		annotation SummarizationSetBy = Automatic

	/// Track del pipeline que produjo la fila: Producción o Calidad. Clave de la dimensión Ambiente.
	column 'Ambiente Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1f1e1d1c-1b1a-4901-8801-770066005502
		summarizeBy: none
		sourceColumn: AMBIENTE

	/// Banda baja LOYO (P25) del volumen 1P en espacio Precio Neto (motor Isotónica).
	column 'Vol P25 (MBPE)'
		dataType: double
		formatString: #,##0.0
		lineageTag: c2be9724-2436-42c9-a8c6-a4e9bbbf2b18
		summarizeBy: sum
		sourceColumn: VOL_P25_MBPE

	/// Banda alta LOYO (P75) del volumen 1P en espacio Precio Neto (motor Isotónica).
	column 'Vol P75 (MBPE)'
		dataType: double
		formatString: #,##0.0
		lineageTag: eb25a1a9-8edc-4e59-bcc5-af115e35ce4f
		summarizeBy: sum
		sourceColumn: VOL_P75_MBPE

	partition Partition = m
		mode: import
		source =
				let
				    fCarga = (ruta as text, ambiente as text) as table =>
				        let
				            Origen = Csv.Document(File.Contents(ruta), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				            Prom = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				            SinBOM = Table.TransformColumnNames(Prom, each Text.Replace(_, Character.FromNumber(65279), "")),
				            ConAmb = Table.AddColumn(SinBOM, "AMBIENTE", each ambiente, type text)
				        in
				            ConAmb,
				    Prod = fCarga(RutaBase & "\resultados\output_matriz_modelo1.csv", "Producción"),
				    Cal = fCarga(RutaBase & "\resultados_calidad\output_matriz_modelo1.csv", "Calidad"),
				    Union = Table.Combine({Prod, Cal}),
				    Slim = Table.SelectColumns(Union, {"CAMPO", "MOTOR", "PRECIO_ACEITE_USD_BBL", "DELTA_ANCLADO_MBPE", "VOLUMEN_1P_PREDICHO_MBPE", "VOL_P25_MBPE", "VOL_P75_MBPE", "AMBIENTE"}),
				    Tipos = Table.TransformColumnTypes(Slim, {{"CAMPO", type text}, {"MOTOR", type text}, {"PRECIO_ACEITE_USD_BBL", type number}, {"DELTA_ANCLADO_MBPE", type number}, {"VOLUMEN_1P_PREDICHO_MBPE", type number}, {"VOL_P25_MBPE", type number}, {"VOL_P75_MBPE", type number}, {"AMBIENTE", type text}}, "en-US")
				in
				    Tipos

