/// FACT de curva M2: grilla Precio Aceite vs Brent por Campo × Ambiente (recta α + β·Brent evaluada).
/// Los coeficientes y bondad de ajuste (Alpha, Beta, R², MAE LOO) viven en la DIM 'Modelo Campo'.
table 'Diagnóstico M2'
	lineageTag: d3e8277e-66f6-4469-9d60-6c41061adc76

	column 'Campo Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 7f2e72c8-d333-401d-a705-618c172791b4
		summarizeBy: none
		sourceColumn: CAMPO

	column 'Brent Clave (USD/bbl)'
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: 742a146f-7e2a-4d7d-825b-bf929f86a6e8
		summarizeBy: none
		sourceColumn: BRENT_USD_BBL

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Track del pipeline que produjo la fila: Producción o Calidad. Clave de la dimensión Ambiente.
	column 'Ambiente Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1f1e1d1c-1b1a-4901-8801-770066005503
		summarizeBy: none
		sourceColumn: AMBIENTE

	/// Predicho = α + β·Brent.
	column 'Precio Aceite (USD/bbl)'
		dataType: double
		formatString: $#,##0.00
		lineageTag: 0df887ad-6333-449c-9ec5-24ca4e7f3fd6
		summarizeBy: sum
		sourceColumn: PRECIO_ACEITE_USD_BBL

		annotation SummarizationSetBy = Automatic

	partition Partition = m
		mode: import
		source =
				let
				    fCarga = (ruta as text, ambiente as text) as table =>
				        let
				            Origen = Csv.Document(File.Contents(ruta), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				            Prom = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				            SinBOM = Table.TransformColumnNames(Prom, each Text.Replace(_, Character.FromNumber(65279), "")),
				            ConAmb = Table.AddColumn(SinBOM, "AMBIENTE", each ambiente, type text)
				        in
				            ConAmb,
				    Prod = fCarga(RutaBase & "\resultados\output_matriz_modelo2.csv", "Producción"),
				    Cal = fCarga(RutaBase & "\resultados_calidad\output_matriz_modelo2.csv", "Calidad"),
				    Union = Table.Combine({Prod, Cal}),
				    Slim = Table.SelectColumns(Union, {"CAMPO", "BRENT_USD_BBL", "PRECIO_ACEITE_USD_BBL", "AMBIENTE"}),
				    Tipos = Table.TransformColumnTypes(Slim, {{"CAMPO", type text}, {"BRENT_USD_BBL", type number}, {"PRECIO_ACEITE_USD_BBL", type number}, {"AMBIENTE", type text}}, "en-US")
				in
				    Tipos
