/// FACT central: predicción de reservas 1P. Grano = 1 fila por Campo × Motor × Brent × Ambiente.
/// Cadena M2 (Brent→Precio Neto) → M1 (Precio→Volumen). Solo columnas que VARÍAN por fila;
/// los atributos constantes por campo viven en la DIM 'Modelo Campo' y los de la corrida en 'Corrida'.
table Predicción
	lineageTag: 8db16789-46ec-4b7d-a9c6-c163847f5e68

	column 'Campo Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 5134e7e4-e139-40dc-87cd-1ef87ff37857
		summarizeBy: none
		sourceColumn: CAMPO

	column 'Motor Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 463b13d8-0154-41e0-b267-0f38d9a28133
		summarizeBy: none
		sourceColumn: MOTOR

	column 'Brent Clave (USD/bbl)'
		dataType: double
		isHidden
		isAvailableInMdx: false
		lineageTag: fe6b78d9-fe77-4470-ab91-66acb072a89e
		summarizeBy: none
		sourceColumn: BRENT_USD_BBL

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	/// Precio Neto estimado por el Modelo 2 (α + β·Brent) al Brent del escenario. Es el Precio Neto (Brent − descuentos calidad y transporte) que recibe el campo, no el Brent.
	column 'Precio Neto M2 (USD/bbl)'
		dataType: double
		formatString: $#,##0.00
		displayFolder: 2. Precios
		lineageTag: 1e9326a7-ede1-44a3-80f8-201c0dfcd09f
		summarizeBy: sum
		sourceColumn: PRECIO_NETO_EFECTIVO_USD_BBL

		annotation SummarizationSetBy = Automatic

	/// Delta anclado de reservas = f(p) − f(p_ref).
	column 'Delta Predicho (MBPE)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: 44c2af04-dabd-49c0-907c-53228cbc1e5e
		summarizeBy: sum
		sourceColumn: DELTA_PRED_MBPE

		annotation SummarizationSetBy = Automatic

	/// max(baseline + delta, 0). Hard-zero bajo breakeven.
	column 'Volumen 1P Predicho (MBPE)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: 3c856260-17a7-46d0-8b03-7e00b7dfce07
		summarizeBy: sum
		sourceColumn: VOLUMEN_1P_PREDICHO_MBPE

		annotation SummarizationSetBy = Automatic

	column 'Delta vs Base (MBPE)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: b74653d8-e9f9-4c2e-8952-933f4d5ad787
		summarizeBy: sum
		sourceColumn: DELTA_VS_BASE_MBPE

		annotation SummarizationSetBy = Automatic

	column 'Delta vs Base (%)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: 47bd1a67-dba2-4bf9-ae4b-876a51516eb0
		summarizeBy: sum
		sourceColumn: DELTA_VS_BASE_PCT

		annotation SummarizationSetBy = Automatic

	/// Precio Neto ≥ Precio de Equilibrio (conserva algo de 1P).
	column 'Es Viable'
		dataType: boolean
		displayFolder: 4. Viabilidad
		lineageTag: e53fa380-2783-4c4a-b88a-e4db2f704198
		summarizeBy: none
		sourceColumn: ES_VIABLE

	column 'Es Full Reservas'
		dataType: boolean
		displayFolder: 4. Viabilidad
		lineageTag: 7aadd537-56cb-4698-acd2-b187f086e0bb
		summarizeBy: none
		sourceColumn: ES_FULL_RESERVAS

	/// Brent fuera de la banda observada del campo ± $5.
	column 'Es Extrapolado'
		dataType: boolean
		displayFolder: 4. Viabilidad
		lineageTag: abe19396-2ed8-45d5-97ae-870fa9925091
		summarizeBy: none
		sourceColumn: ES_EXTRAPOLADO

	/// Brent por ENCIMA del techo de la banda del deck: isotónica saturada, el volumen es techo de recuperación (sesgo de recuperación). Ver DICCIONARIO §7.
	column 'Es Clipped'
		dataType: boolean
		displayFolder: 4. Viabilidad
		lineageTag: 57325f27-bc69-4af3-a990-ef6514d303cb
		summarizeBy: none
		sourceColumn: ES_CLIPPED

		annotation SummarizationSetBy = Automatic

	/// Track del pipeline que produjo la fila: Producción o Calidad. Clave de la dimensión Ambiente.
	column 'Ambiente Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1f1e1d1c-1b1a-4901-8801-770066005501
		summarizeBy: none
		sourceColumn: AMBIENTE

	/// Banda baja LOYO (P25) del volumen 1P. Poblada en ambos tracks desde la promoción
	/// 2026-07-15 (null solo para campos con menos de 2 vigencias reales, motor Suave, o
	/// volumen predicho = 0 — ver 04_pbi_export.py).
	column 'Vol P25 (MBPE)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: 1f1e1d1c-1b1a-4901-8801-770066005510
		summarizeBy: sum
		sourceColumn: VOL_P25_MBPE

		annotation SummarizationSetBy = Automatic

	/// Banda alta LOYO (P75) del volumen 1P. Poblada en ambos tracks desde la promoción
	/// 2026-07-15 (mismas excepciones que 'Vol P25 (MBPE)').
	column 'Vol P75 (MBPE)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: 1f1e1d1c-1b1a-4901-8801-770066005511
		summarizeBy: sum
		sourceColumn: VOL_P75_MBPE

		annotation SummarizationSetBy = Automatic

	/// Vol P75 - Vol P25 en el punto de la fila (ancho de la banda LOYO).
	column 'Ancho Banda LOYO (MBPE)'
		dataType: double
		formatString: #,##0.0
		displayFolder: 1. Volúmenes
		lineageTag: 7f4f5018-4564-4e6a-ab91-314ba7fa085f
		summarizeBy: sum
		sourceColumn: ANCHO_BANDA_LOYO_MBPE

	partition Partition = m
		mode: import
		source =
				let
				    fCarga = (ruta as text, ambiente as text) as table =>
				        let
				            Origen = Csv.Document(File.Contents(ruta), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				            Prom = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				            SinBOM = Table.TransformColumnNames(Prom, each Text.Replace(_, Character.FromNumber(65279), "")),
				            ConAmb = Table.AddColumn(SinBOM, "AMBIENTE", each ambiente, type text)
				        in
				            ConAmb,
				    Prod = fCarga(RutaBase & "\resultados\output_matriz_prediccion.csv", "Producción"),
				    Cal = fCarga(RutaBase & "\resultados_calidad\output_matriz_prediccion.csv", "Calidad"),
				    Union = Table.Combine({Prod, Cal}),
				    // Estrella: el CSV sigue denormalizado (compatibilidad tests/snapshots) pero el
				    // modelo solo carga las columnas que varían por fila; el resto vive en 'Modelo Campo'/'Corrida'.
				    Slim = Table.SelectColumns(Union, {"CAMPO", "MOTOR", "BRENT_USD_BBL", "PRECIO_NETO_EFECTIVO_USD_BBL", "DELTA_PRED_MBPE", "VOLUMEN_1P_PREDICHO_MBPE", "DELTA_VS_BASE_MBPE", "DELTA_VS_BASE_PCT", "ES_VIABLE", "ES_FULL_RESERVAS", "ES_EXTRAPOLADO", "ES_CLIPPED", "VOL_P25_MBPE", "VOL_P75_MBPE", "ANCHO_BANDA_LOYO_MBPE", "AMBIENTE"}),
				    Tipos = Table.TransformColumnTypes(Slim, {{"CAMPO", type text}, {"MOTOR", type text}, {"BRENT_USD_BBL", type number}, {"PRECIO_NETO_EFECTIVO_USD_BBL", type number}, {"DELTA_PRED_MBPE", type number}, {"VOLUMEN_1P_PREDICHO_MBPE", type number}, {"DELTA_VS_BASE_MBPE", type number}, {"DELTA_VS_BASE_PCT", type number}, {"ES_VIABLE", type logical}, {"ES_FULL_RESERVAS", type logical}, {"ES_EXTRAPOLADO", type logical}, {"ES_CLIPPED", type logical}, {"VOL_P25_MBPE", type number}, {"VOL_P75_MBPE", type number}, {"ANCHO_BANDA_LOYO_MBPE", type number}, {"AMBIENTE", type text}}, "en-US")
				in
				    Tipos

	annotation PBI_ResultType = Table

