/// Puntos del Modelo 1 para replicar los plots de datos/staging: curva del modelo (Isotónica/Suave) + puntos reales por año + ancla actual. La columna Serie separa modelo / real / ancla; Año colorea los reales por vigencia. No incluye sintéticos ni breakeven.
table 'Puntos M1'
	lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b10

	column IDX
		dataType: int64
		isHidden
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b11
		summarizeBy: none
		sourceColumn: IDX

	/// Clave de campo (une con la dimensión Campo).
	column CAMPO
		dataType: string
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b12
		summarizeBy: none
		sourceColumn: CAMPO

	/// Serie con detalle: Isotónica / Suave (modelo), Sensibilidad {año}-Q{n} (dato observado por trimestre), Baseline {año} (cierre oficial anual), Ancla (punto actual). Ver 'Serie Color' para la agrupación por año usada en leyenda/color.
	column Serie
		dataType: string
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b13
		summarizeBy: none
		sourceColumn: SERIE

	/// Año de la vigencia del punto real (vacío en curva y ancla).
	column Año
		dataType: int64
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b14
		summarizeBy: none
		sourceColumn: AÑO

	/// Precio Neto (eje X). En reales es el neto observado; en la curva la rejilla del modelo.
	column 'Precio Neto (USD/bbl)'
		dataType: double
		formatString: $#,##0.00
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b15
		summarizeBy: none
		sourceColumn: PRECIO_NETO_USD_BBL

	/// ΔReservas vs baseline (eje Y del panel delta).
	column 'Delta (MBPE)'
		dataType: double
		formatString: #,##0.0
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b16
		summarizeBy: sum
		sourceColumn: DELTA_MBPE

	/// Volumen 1P absoluto = baseline + Δ (eje Y del panel volumen).
	column 'Volumen 1P (MBPE)'
		dataType: double
		formatString: #,##0.0
		lineageTag: 3c1a9f42-6b28-4e71-9d05-1a7e4c8f2b17
		summarizeBy: sum
		sourceColumn: VOLUMEN_MBPE

	/// Track del pipeline que produjo la fila: Producción o Calidad. Clave de la dimensión Ambiente.
	column 'Ambiente Clave'
		dataType: string
		isHidden
		isAvailableInMdx: false
		lineageTag: 1f1e1d1c-1b1a-4901-8801-770066005504
		summarizeBy: none
		sourceColumn: AMBIENTE

	/// Agrupa Serie por año para leyenda/color (ej. 'Sensibilidad 2024' agrupa Q1-Q4; Serie conserva el detalle del Q).
	column 'Serie Color'
		dataType: string
		lineageTag: 17b4d33e-5604-4412-b7c2-419e2b0aeec5
		summarizeBy: none
		sourceColumn: SERIE_COLOR

	partition Partition = m
		mode: import
		source =
				let
				    fCarga = (ruta as text, ambiente as text) as table =>
				        let
				            Origen = Csv.Document(File.Contents(ruta), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				            Prom = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				            SinBOM = Table.TransformColumnNames(Prom, each Text.Replace(_, Character.FromNumber(65279), "")),
				            ConAmb = Table.AddColumn(SinBOM, "AMBIENTE", each ambiente, type text)
				        in
				            ConAmb,
				    Prod = fCarga(RutaBase & "\resultados\output_puntos_m1.csv", "Producción"),
				    Cal = fCarga(RutaBase & "\resultados_calidad\output_puntos_m1.csv", "Calidad"),
				    Union = Table.Combine({Prod, Cal}),
				    Tipos = Table.TransformColumnTypes(Union, {{"IDX", Int64.Type}, {"CAMPO", type text}, {"SERIE", type text}, {"SERIE_COLOR", type text}, {"AÑO", Int64.Type}, {"PRECIO_NETO_USD_BBL", type number}, {"DELTA_MBPE", type number}, {"VOLUMEN_MBPE", type number}, {"AMBIENTE", type text}}, "en-US")
				in
				    Tipos

